// This file is generated by the Supabase CLI and should not be hand-edited.
// Run: npx supabase gen types typescript --project-id <your-project-id> > src/lib/supabase/database.types.ts
//
// Stub until Milestone 2 schema is applied.
export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
};
