// This file is generated by the Supabase CLI and should not be hand-edited.
// Run: npx supabase gen types typescript --project-id <your-project-id> > src/lib/supabase/database.types.ts
//
// Hand-authored to match supabase/migrations/0001_household_and_care_recipient.sql,
// 0002_feeding.sql, 0003_caregiver_invites.sql, 0004_diapers.sql,
// 0005_medications.sql, and 0006_care_notes.sql (the project isn't
// CLI-linked yet) — regenerate via the CLI once it is.

type HouseholdRow = {
  id: string;
  name: string;
  owner_id: string;
  created_at: string;
};

type HouseholdMemberRow = {
  id: string;
  household_id: string;
  user_id: string;
  role: string;
  status: string;
  created_at: string;
};

type CareRecipientRow = {
  id: string;
  household_id: string;
  name: string;
  date_of_birth: string | null;
  feed_interval_minutes: number;
  created_at: string;
};

// Postgres `numeric` comes back from supabase-js as a string, not a number,
// to avoid float precision loss — amount is typed `string` here on purpose.
type FeedRow = {
  id: string;
  care_recipient_id: string;
  amount: string;
  unit: string;
  fed_at: string;
  created_by: string;
  created_at: string;
};

type FeedPresetRow = {
  id: string;
  care_recipient_id: string;
  amount: string;
  unit: string;
  created_at: string;
};

type HouseholdInviteRow = {
  id: string;
  household_id: string;
  email: string;
  invited_by: string;
  created_at: string;
  expires_at: string;
  accepted_at: string | null;
};

type HouseholdCaregiverRow = {
  user_id: string;
  email: string;
  role: string;
  joined_at: string;
};

type DiaperRow = {
  id: string;
  care_recipient_id: string;
  type: string;
  changed_at: string;
  created_by: string;
  created_at: string;
};

// Postgres `time[]` comes back from supabase-js as a plain string array
// (e.g. ["08:00:00", "20:00:00"]), not a typed time array.
type MedicationRow = {
  id: string;
  care_recipient_id: string;
  name: string;
  dosage: string;
  instructions: string | null;
  is_prn: boolean;
  schedule_times: string[];
  deactivated_at: string | null;
  created_at: string;
};

type MedicationEventRow = {
  id: string;
  medication_id: string;
  status: string;
  scheduled_for: string | null;
  given_at: string;
  created_by: string;
  created_at: string;
};

type CareNoteRow = {
  id: string;
  care_recipient_id: string;
  note: string;
  is_notable: boolean;
  created_by: string;
  created_at: string;
};

export type Database = {
  public: {
    Tables: {
      households: {
        Row: HouseholdRow;
        Insert: Partial<HouseholdRow> & { name: string; owner_id: string };
        Update: Partial<HouseholdRow>;
        Relationships: [];
      };
      household_members: {
        Row: HouseholdMemberRow;
        Insert: Partial<HouseholdMemberRow> & {
          household_id: string;
          user_id: string;
          role: string;
        };
        Update: Partial<HouseholdMemberRow>;
        Relationships: [
          {
            foreignKeyName: 'household_members_household_id_fkey';
            columns: ['household_id'];
            isOneToOne: false;
            referencedRelation: 'households';
            referencedColumns: ['id'];
          },
        ];
      };
      care_recipients: {
        Row: CareRecipientRow;
        Insert: Partial<CareRecipientRow> & { household_id: string; name: string };
        Update: Partial<CareRecipientRow>;
        Relationships: [
          {
            foreignKeyName: 'care_recipients_household_id_fkey';
            columns: ['household_id'];
            isOneToOne: false;
            referencedRelation: 'households';
            referencedColumns: ['id'];
          },
        ];
      };
      feeds: {
        Row: FeedRow;
        Insert: Partial<FeedRow> & {
          care_recipient_id: string;
          amount: string;
          unit: string;
          created_by: string;
        };
        Update: Partial<FeedRow>;
        Relationships: [
          {
            foreignKeyName: 'feeds_care_recipient_id_fkey';
            columns: ['care_recipient_id'];
            isOneToOne: false;
            referencedRelation: 'care_recipients';
            referencedColumns: ['id'];
          },
        ];
      };
      feed_presets: {
        Row: FeedPresetRow;
        Insert: Partial<FeedPresetRow> & {
          care_recipient_id: string;
          amount: string;
          unit: string;
        };
        Update: Partial<FeedPresetRow>;
        Relationships: [
          {
            foreignKeyName: 'feed_presets_care_recipient_id_fkey';
            columns: ['care_recipient_id'];
            isOneToOne: false;
            referencedRelation: 'care_recipients';
            referencedColumns: ['id'];
          },
        ];
      };
      household_invites: {
        Row: HouseholdInviteRow;
        Insert: Partial<HouseholdInviteRow> & {
          household_id: string;
          email: string;
          invited_by: string;
        };
        Update: Partial<HouseholdInviteRow>;
        Relationships: [
          {
            foreignKeyName: 'household_invites_household_id_fkey';
            columns: ['household_id'];
            isOneToOne: false;
            referencedRelation: 'households';
            referencedColumns: ['id'];
          },
        ];
      };
      diapers: {
        Row: DiaperRow;
        Insert: Partial<DiaperRow> & {
          care_recipient_id: string;
          type: string;
          created_by: string;
        };
        Update: Partial<DiaperRow>;
        Relationships: [
          {
            foreignKeyName: 'diapers_care_recipient_id_fkey';
            columns: ['care_recipient_id'];
            isOneToOne: false;
            referencedRelation: 'care_recipients';
            referencedColumns: ['id'];
          },
        ];
      };
      medications: {
        Row: MedicationRow;
        Insert: Partial<MedicationRow> & {
          care_recipient_id: string;
          name: string;
          dosage: string;
        };
        Update: Partial<MedicationRow>;
        Relationships: [
          {
            foreignKeyName: 'medications_care_recipient_id_fkey';
            columns: ['care_recipient_id'];
            isOneToOne: false;
            referencedRelation: 'care_recipients';
            referencedColumns: ['id'];
          },
        ];
      };
      medication_events: {
        Row: MedicationEventRow;
        Insert: Partial<MedicationEventRow> & {
          medication_id: string;
          status: string;
          created_by: string;
        };
        Update: Partial<MedicationEventRow>;
        Relationships: [
          {
            foreignKeyName: 'medication_events_medication_id_fkey';
            columns: ['medication_id'];
            isOneToOne: false;
            referencedRelation: 'medications';
            referencedColumns: ['id'];
          },
        ];
      };
      care_notes: {
        Row: CareNoteRow;
        Insert: Partial<CareNoteRow> & {
          care_recipient_id: string;
          note: string;
          created_by: string;
        };
        Update: Partial<CareNoteRow>;
        Relationships: [
          {
            foreignKeyName: 'care_notes_care_recipient_id_fkey';
            columns: ['care_recipient_id'];
            isOneToOne: false;
            referencedRelation: 'care_recipients';
            referencedColumns: ['id'];
          },
        ];
      };
    };
    Views: Record<string, never>;
    Functions: {
      is_household_member: {
        Args: { target_household_id: string };
        Returns: boolean;
      };
      create_household: {
        Args: { household_name: string };
        Returns: HouseholdRow;
      };
      update_feed_interval_minutes: {
        Args: { target_care_recipient_id: string; new_interval_minutes: number };
        Returns: CareRecipientRow;
      };
      accept_household_invite: {
        Args: { target_invite_id: string };
        Returns: HouseholdMemberRow;
      };
      list_household_caregivers: {
        Args: { target_household_id: string };
        Returns: HouseholdCaregiverRow[];
      };
    };
    Enums: Record<string, never>;
  };
};
