// This file is generated by the Supabase CLI and should not be hand-edited.
// Run: npx supabase gen types typescript --project-id <your-project-id> > src/lib/supabase/database.types.ts
//
// Hand-authored to match supabase/migrations/0001_household_and_care_recipient.sql
// (the project isn't CLI-linked yet) — regenerate via the CLI once it is.

type HouseholdRow = {
  id: string;
  name: string;
  owner_id: string;
  created_at: string;
};

type HouseholdMemberRow = {
  id: string;
  household_id: string;
  user_id: string;
  role: string;
  status: string;
  created_at: string;
};

type CareRecipientRow = {
  id: string;
  household_id: string;
  name: string;
  date_of_birth: string | null;
  created_at: string;
};

export type Database = {
  public: {
    Tables: {
      households: {
        Row: HouseholdRow;
        Insert: Partial<HouseholdRow> & { name: string; owner_id: string };
        Update: Partial<HouseholdRow>;
        Relationships: [];
      };
      household_members: {
        Row: HouseholdMemberRow;
        Insert: Partial<HouseholdMemberRow> & {
          household_id: string;
          user_id: string;
          role: string;
        };
        Update: Partial<HouseholdMemberRow>;
        Relationships: [
          {
            foreignKeyName: 'household_members_household_id_fkey';
            columns: ['household_id'];
            isOneToOne: false;
            referencedRelation: 'households';
            referencedColumns: ['id'];
          },
        ];
      };
      care_recipients: {
        Row: CareRecipientRow;
        Insert: Partial<CareRecipientRow> & { household_id: string; name: string };
        Update: Partial<CareRecipientRow>;
        Relationships: [
          {
            foreignKeyName: 'care_recipients_household_id_fkey';
            columns: ['household_id'];
            isOneToOne: false;
            referencedRelation: 'households';
            referencedColumns: ['id'];
          },
        ];
      };
    };
    Views: Record<string, never>;
    Functions: {
      is_household_member: {
        Args: { target_household_id: string };
        Returns: boolean;
      };
      create_household: {
        Args: { household_name: string };
        Returns: HouseholdRow;
      };
    };
    Enums: Record<string, never>;
  };
};
