export const DEFAULT_FEED_INTERVAL_MINUTES = 180;
export const FEED_DUE_SOON_MINUTES = 15;
export const FEED_OVERDUE_GRACE_MINUTES = 15;
export const MIN_FEED_INTERVAL_MINUTES = 1;
export const MAX_FEED_INTERVAL_MINUTES = 1440;
